meta:
  url:
  title: What is Git & GitHub?
  description: Introduction to Git & GitHub
  siteName:
  sns: ['twitter']
slide:
  loop: false
  ui:
    sidebar: true
    vertical: false
    pagination: # bullets | progressbar | fraction
    effect: # fade | cube | flip
  code:
    # https://prismjs.com/
    plugins: []
    theme: default # coy | dark | funky | okaidia | solarizedlight | tomorrow | twilight
